-- Drop Tables
DROP TABLE IF EXISTS staging_events CASCADE;
DROP TABLE IF EXISTS staging_songs CASCADE;
DROP TABLE IF EXISTS songplays CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS songs CASCADE;
DROP TABLE IF EXISTS artists CASCADE;
DROP TABLE IF EXISTS time CASCADE;

-- Create Tables
CREATE TABLE IF NOT EXISTS staging_events ( 
                                    artist TEXT,
                                    auth VARCHAR(MAX),
                                    firstName TEXT,
                                    gender CHAR(1),
                                    itemInSession int,
                                    lastName TEXT,
                                    length NUMERIC,
                                    level CHAR(4),
                                    location TEXT,
                                    method CHAR(3),
                                    page VARCHAR(MAX),
                                    registration bigint,
                                    session_id int,
                                    song TEXT,
                                    status smallint,
                                    ts bigint,
                                    userAgent TEXT,
                                    user_id int
                                    ); 
CREATE TABLE IF NOT EXISTS staging_songs ( 
                                    num_songs int,
                                    artist_id VARCHAR(MAX),
                                    artist_latitude DOUBLE PRECISION,
                                    artist_longitude DOUBLE PRECISION,
                                    artist_location TEXT,
                                    artist_name TEXT,
                                    song_id VARCHAR(MAX),
                                    title TEXT,
                                    duration NUMERIC,
                                    year int
                                    );
CREATE TABLE IF NOT EXISTS songplays (
                                    songplay_id int IDENTITY(0,1) PRIMARY KEY,
                                    start_time bigint NOT NULL,
                                    user_id int NOT NULL,
                                    level CHAR(4) NOT NULL,
                                    song_id VARCHAR(MAX) NOT NULL,
                                    artist_id VARCHAR(MAX) NOT NULL,
                                    session_id int NOT NULL,
                                    location TEXT,
                                    user_agent TEXT
                                    );
CREATE TABLE IF NOT EXISTS users (
                                    user_id int GENERATED BY DEFAULT AS IDENTITY(0,1) PRIMARY KEY,
                                    first_name TEXT NOT NULL,
                                    last_name TEXT NOT NULL,
                                    gender CHAR(1) NOT NULL,
                                    level CHAR(4) NOT NULL
                                    ); 
CREATE TABLE IF NOT EXISTS songs (
                                    song_id VARCHAR(MAX) PRIMARY KEY,
                                    title TEXT NOT NULL,
                                    artist_id VARCHAR(20) NOT NULL,
                                    year int NOT NULL,
                                    duration NUMERIC NOT NULL
                                    );
CREATE TABLE IF NOT EXISTS artists (
                                    artist_id VARCHAR(MAX) PRIMARY KEY,
                                    name TEXT NOT NULL,
                                    location TEXT,
                                    latitude DOUBLE PRECISION,
                                    longitude DOUBLE PRECISION
                                    );
CREATE TABLE IF NOT EXISTS time (
                                    start_time TIMESTAMP PRIMARY KEY,
                                    hour smallint NOT NULL,
                                    day smallint NOT NULL,
                                    week smallint NOT NULL,
                                    month CHAR(3) NOT NULL,
                                    year int NOT NULL,
                                    weekday CHAR(3) NOT NULL
                                    );

